"""Blender UV Bake material implementation facade."""

from .config import UVBakeMaterialConfig
from .constants import (
    DEFAULT_ALLOW_BACKFACE_FALLBACK,
    DEFAULT_ANGLE_LIMIT_DEGREES,
    DEFAULT_ENABLE_VISIBILITY,
    DEFAULT_FACING_POWER,
    DEFAULT_ISLAND_MARGIN,
    DEFAULT_MAX_CONTRIBUTORS,
    DEFAULT_MIN_FACING,
    DEFAULT_PADDING_PIXELS,
    DEFAULT_RELATIVE_SCORE_CUTOFF,
    DEFAULT_REUSE_EXISTING_UV,
    DEFAULT_ROUGHNESS,
    DEFAULT_SAMPLES_PER_AXIS,
    DEFAULT_TEXTURE_SIZE,
    DEFAULT_UV_LAYER_NAME,
    DEFAULT_WEIGHT_POWER,
    IMPLEMENTATION_ID,
    MATERIAL_MODE,
    MAX_SMART_PROJECT_MARGIN_TEXELS,
)
from .diagnostics import UVBakeMaterialOutput, UVLayoutDiagnostics
from .implementation import UVBakeImplementation
from .settings import require_uv_bake_output

__all__ = (
    "DEFAULT_ALLOW_BACKFACE_FALLBACK", "DEFAULT_ANGLE_LIMIT_DEGREES",
    "DEFAULT_ENABLE_VISIBILITY", "DEFAULT_FACING_POWER", "DEFAULT_ISLAND_MARGIN",
    "DEFAULT_MAX_CONTRIBUTORS", "DEFAULT_MIN_FACING", "DEFAULT_PADDING_PIXELS",
    "DEFAULT_RELATIVE_SCORE_CUTOFF", "DEFAULT_REUSE_EXISTING_UV",
    "DEFAULT_ROUGHNESS", "DEFAULT_SAMPLES_PER_AXIS", "DEFAULT_TEXTURE_SIZE",
    "DEFAULT_UV_LAYER_NAME", "DEFAULT_WEIGHT_POWER", "IMPLEMENTATION_ID",
    "MATERIAL_MODE", "MAX_SMART_PROJECT_MARGIN_TEXELS", "UVBakeImplementation",
    "UVBakeMaterialConfig", "UVBakeMaterialOutput", "UVLayoutDiagnostics",
    "require_uv_bake_output",
)
