from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .config import (
    DEFAULT_COMPARISON_ROOT,
    DEFAULT_GUTTER,
    DEFAULT_IMPLEMENTATIONS,
    DEFAULT_PROFILES,
    DEFAULT_SAMPLES,
    DEFAULT_SIZE,
    DEFAULT_VIEWS,
)

# =========================================================
# CLI
# =========================================================

def _script_arguments() -> list[str]:
    if "--" not in sys.argv:
        return []

    index = sys.argv.index(
        "--"
    )

    return sys.argv[
        index + 1:
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Render side-by-side Meshvenn MATERIAL "
            "implementation comparisons."
        )
    )

    parser.add_argument(
        "--comparison-root",
        type=Path,
        default=(
            DEFAULT_COMPARISON_ROOT
        ),
        help=(
            "Output directory previously generated by "
            "generate_material_comparison.py."
        ),
    )

    parser.add_argument(
        "--sheets",
        nargs="*",
        default=None,
        help=(
            "Optional sheet names. "
            "Example: sheet1 sheet2."
        ),
    )

    parser.add_argument(
        "--profiles",
        nargs="+",
        default=list(
            DEFAULT_PROFILES
        ),
    )

    parser.add_argument(
        "--implementations",
        nargs="+",
        default=list(
            DEFAULT_IMPLEMENTATIONS
        ),
    )

    parser.add_argument(
        "--views",
        type=int,
        default=(
            DEFAULT_VIEWS
        ),
    )

    parser.add_argument(
        "--size",
        type=int,
        default=(
            DEFAULT_SIZE
        ),
    )

    parser.add_argument(
        "--samples",
        type=int,
        default=(
            DEFAULT_SAMPLES
        ),
    )

    parser.add_argument(
        "--gutter",
        type=int,
        default=(
            DEFAULT_GUTTER
        ),
    )

    parser.add_argument(
        "--keep-stills",
        action="store_true",
    )

    parser.add_argument(
        "--reuse-renders",
        action="store_true",
        help=(
            "Reuse existing per-variant contact sheets "
            "instead of rendering them again."
        ),
    )

    parser.add_argument(
        "--continue-on-error",
        action="store_true",
    )

    return parser.parse_args(
        _script_arguments()
    )


# =========================================================
# Validation
# =========================================================

def _unique_ordered(
    values: list[str],
) -> list[str]:
    result: list[str] = []

    seen: set[str] = set()

    for value in values:
        normalized = (
            str(value)
            .strip()
        )

        if not normalized:
            continue

        if normalized in seen:
            continue

        seen.add(
            normalized
        )

        result.append(
            normalized
        )

    return result


def validate_args(
    args: argparse.Namespace,
) -> None:
    args.profiles = [
        value.upper()
        for value
        in _unique_ordered(
            args.profiles
        )
    ]

    args.implementations = (
        _unique_ordered(
            args.implementations
        )
    )

    if not args.profiles:
        raise ValueError(
            (
                "At least one profile "
                "is required."
            )
        )

    if not args.implementations:
        raise ValueError(
            (
                "At least one MATERIAL "
                "implementation is required."
            )
        )

    for profile in (
        args.profiles
    ):
        if profile not in {
            "L2",
            "L4",
            "L8",
            "L10",
        }:
            raise ValueError(
                (
                    "Unsupported profile: "
                    f"{profile}"
                )
            )

    if not (
        4
        <= args.views
        <= 16
    ):
        raise ValueError(
            (
                "views must be "
                "between 4 and 16."
            )
        )

    if args.size < 128:
        raise ValueError(
            (
                "size must be "
                "at least 128."
            )
        )

    if args.samples < 1:
        raise ValueError(
            (
                "samples must be "
                "at least 1."
            )
        )

    if not (
        0
        <= args.gutter
        <= 128
    ):
        raise ValueError(
            (
                "gutter must be "
                "between 0 and 128."
            )
        )
