from __future__ import annotations

import argparse
import json
import math
import shutil
import sys
import time

from array import array
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import bpy


# =========================================================
# Repository
# =========================================================

REPO_ROOT = (
    Path(__file__)
    .resolve()
    .parents[1]
)

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(REPO_ROOT),
    )


from scripts.render_turntable import (
    render_turntable,
)


# =========================================================
# Defaults
# =========================================================

DEFAULT_COMPARISON_ROOT = (
    REPO_ROOT
    / "example"
    / "mascotte"
    / "test1"
    / "material-comparison"
)

DEFAULT_PROFILES = (
    "L2",
    "L4",
    "L8",
    "L10",
)

DEFAULT_IMPLEMENTATIONS = (
    "projected-color-v1.2",
    "uv-bake-v2",
)

DEFAULT_VIEWS = 8

DEFAULT_SIZE = 384

DEFAULT_SAMPLES = 1

DEFAULT_GUTTER = 8

BACKGROUND_COLOR = (
    0.025,
    0.025,
    0.03,
    1.0,
)

DIMENSION_TOLERANCE = 1e-5


# =========================================================
# Variant
# =========================================================

@dataclass(frozen=True)
class Variant:
    sheet: str

    profile: str

    implementation: str

    root: Path

    model_path: Path

    manifest_path: Path

    render_root: Path

    contact_sheet_path: Path

    metadata: dict[str, Any]


# =========================================================
# CLI
# =========================================================

def _script_arguments() -> list[str]:
    if "--" not in sys.argv:
        return []

    index = sys.argv.index(
        "--"
    )

    return sys.argv[
        index + 1:
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Render side-by-side Meshvenn MATERIAL "
            "implementation comparisons."
        )
    )

    parser.add_argument(
        "--comparison-root",
        type=Path,
        default=(
            DEFAULT_COMPARISON_ROOT
        ),
        help=(
            "Output directory previously generated by "
            "generate_material_comparison.py."
        ),
    )

    parser.add_argument(
        "--sheets",
        nargs="*",
        default=None,
        help=(
            "Optional sheet names. "
            "Example: sheet1 sheet2."
        ),
    )

    parser.add_argument(
        "--profiles",
        nargs="+",
        default=list(
            DEFAULT_PROFILES
        ),
    )

    parser.add_argument(
        "--implementations",
        nargs="+",
        default=list(
            DEFAULT_IMPLEMENTATIONS
        ),
    )

    parser.add_argument(
        "--views",
        type=int,
        default=(
            DEFAULT_VIEWS
        ),
    )

    parser.add_argument(
        "--size",
        type=int,
        default=(
            DEFAULT_SIZE
        ),
    )

    parser.add_argument(
        "--samples",
        type=int,
        default=(
            DEFAULT_SAMPLES
        ),
    )

    parser.add_argument(
        "--gutter",
        type=int,
        default=(
            DEFAULT_GUTTER
        ),
    )

    parser.add_argument(
        "--keep-stills",
        action="store_true",
    )

    parser.add_argument(
        "--reuse-renders",
        action="store_true",
        help=(
            "Reuse existing per-variant contact sheets "
            "instead of rendering them again."
        ),
    )

    parser.add_argument(
        "--continue-on-error",
        action="store_true",
    )

    return parser.parse_args(
        _script_arguments()
    )


# =========================================================
# Validation
# =========================================================

def _unique_ordered(
    values: list[str],
) -> list[str]:
    result: list[str] = []

    seen: set[str] = set()

    for value in values:
        normalized = (
            str(value)
            .strip()
        )

        if not normalized:
            continue

        if normalized in seen:
            continue

        seen.add(
            normalized
        )

        result.append(
            normalized
        )

    return result


def validate_args(
    args: argparse.Namespace,
) -> None:
    args.profiles = [
        value.upper()
        for value
        in _unique_ordered(
            args.profiles
        )
    ]

    args.implementations = (
        _unique_ordered(
            args.implementations
        )
    )

    if not args.profiles:
        raise ValueError(
            (
                "At least one profile "
                "is required."
            )
        )

    if not args.implementations:
        raise ValueError(
            (
                "At least one MATERIAL "
                "implementation is required."
            )
        )

    for profile in (
        args.profiles
    ):
        if profile not in {
            "L2",
            "L4",
            "L8",
            "L10",
        }:
            raise ValueError(
                (
                    "Unsupported profile: "
                    f"{profile}"
                )
            )

    if not (
        4
        <= args.views
        <= 16
    ):
        raise ValueError(
            (
                "views must be "
                "between 4 and 16."
            )
        )

    if args.size < 128:
        raise ValueError(
            (
                "size must be "
                "at least 128."
            )
        )

    if args.samples < 1:
        raise ValueError(
            (
                "samples must be "
                "at least 1."
            )
        )

    if not (
        0
        <= args.gutter
        <= 128
    ):
        raise ValueError(
            (
                "gutter must be "
                "between 0 and 128."
            )
        )


# =========================================================
# JSON
# =========================================================

def read_json(
    path: Path,
) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(
            (
                "Missing JSON file: "
                f"{path}"
            )
        )

    value = json.loads(
        path.read_text(
            encoding="utf-8"
        )
    )

    if not isinstance(
        value,
        dict,
    ):
        raise TypeError(
            (
                "Expected JSON object: "
                f"{path}"
            )
        )

    return value


def write_json(
    path: Path,
    value: Any,
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_text(
        json.dumps(
            value,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )


# =========================================================
# Discovery
# =========================================================

def discover_sheets(
    comparison_root: Path,
    requested: list[str] | None,
) -> list[str]:
    if not comparison_root.is_dir():
        raise FileNotFoundError(
            (
                "Comparison directory "
                "does not exist: "
                f"{comparison_root}"
            )
        )

    available = sorted(
        path.name
        for path
        in comparison_root.iterdir()
        if (
            path.is_dir()
            and path.name.startswith(
                "sheet"
            )
        )
    )

    if not available:
        raise RuntimeError(
            (
                "No sheet directories found "
                f"in {comparison_root}"
            )
        )

    if not requested:
        return available

    normalized = {
        Path(value).stem
        for value
        in requested
        if str(value).strip()
    }

    selected = [
        name
        for name
        in available
        if name in normalized
    ]

    missing = sorted(
        normalized
        - set(
            selected
        )
    )

    if missing:
        raise ValueError(
            (
                "Unknown sheets: "
                + ", ".join(
                    missing
                )
            )
        )

    return selected


# =========================================================
# Variants
# =========================================================

def load_variant(
    comparison_root: Path,
    *,
    sheet: str,
    profile: str,
    implementation: str,
) -> Variant:
    root = (
        comparison_root
        / sheet
        / profile
        / implementation
    )

    model_path = (
        root
        / "model.glb"
    )

    manifest_path = (
        root
        / "variant.json"
    )

    if not model_path.is_file():
        raise FileNotFoundError(
            (
                "Missing comparison model: "
                f"{model_path}"
            )
        )

    metadata = (
        read_json(
            manifest_path
        )
    )

    render_root = (
        root
        / "render"
    )

    contact_sheet_path = (
        render_root
        / "contact_sheet.png"
    )

    return Variant(
        sheet=sheet,

        profile=profile,

        implementation=(
            implementation
        ),

        root=root,

        model_path=(
            model_path
        ),

        manifest_path=(
            manifest_path
        ),

        render_root=(
            render_root
        ),

        contact_sheet_path=(
            contact_sheet_path
        ),

        metadata=(
            metadata
        ),
    )


# =========================================================
# Geometry parity
# =========================================================

def _geometry_signature(
    variant: Variant,
) -> tuple[
    int,
    int,
    tuple[
        float,
        float,
        float,
    ],
]:
    geometry = (
        variant
        .metadata
        .get(
            "geometry"
        )
    )

    if not isinstance(
        geometry,
        dict,
    ):
        raise RuntimeError(
            (
                "Variant has no geometry "
                f"metadata: {variant.root}"
            )
        )

    vertices = int(
        geometry[
            "vertices"
        ]
    )

    faces = int(
        geometry[
            "faces"
        ]
    )

    raw_dimensions = (
        geometry[
            "dimensions"
        ]
    )

    if (
        not isinstance(
            raw_dimensions,
            list,
        )
        or len(
            raw_dimensions
        )
        != 3
    ):
        raise RuntimeError(
            (
                "Invalid dimensions in "
                f"{variant.manifest_path}"
            )
        )

    dimensions = (
        float(
            raw_dimensions[0]
        ),
        float(
            raw_dimensions[1]
        ),
        float(
            raw_dimensions[2]
        ),
    )

    return (
        vertices,
        faces,
        dimensions,
    )


def validate_geometry_parity(
    variants: list[
        Variant
    ],
) -> None:
    """
    MATERIAL comparison is only useful when every variant
    uses exactly the same geometry.

    Vertex/face counts must match exactly.

    Dimensions may differ only by tiny floating-point noise.
    """

    if len(
        variants
    ) <= 1:
        return

    reference = (
        variants[
            0
        ]
    )

    (
        reference_vertices,
        reference_faces,
        reference_dimensions,
    ) = (
        _geometry_signature(
            reference
        )
    )

    for variant in (
        variants[
            1:
        ]
    ):
        (
            vertices,
            faces,
            dimensions,
        ) = (
            _geometry_signature(
                variant
            )
        )

        if (
            vertices
            != reference_vertices
        ):
            raise RuntimeError(
                (
                    "Geometry parity failure "
                    f"for {variant.sheet}/"
                    f"{variant.profile}: "
                    f"{reference.implementation} has "
                    f"{reference_vertices} vertices, "
                    f"{variant.implementation} has "
                    f"{vertices}."
                )
            )

        if faces != reference_faces:
            raise RuntimeError(
                (
                    "Geometry parity failure "
                    f"for {variant.sheet}/"
                    f"{variant.profile}: "
                    f"{reference.implementation} has "
                    f"{reference_faces} faces, "
                    f"{variant.implementation} has "
                    f"{faces}."
                )
            )

        for axis in range(
            3
        ):
            if not math.isclose(
                dimensions[
                    axis
                ],
                reference_dimensions[
                    axis
                ],
                rel_tol=(
                    DIMENSION_TOLERANCE
                ),
                abs_tol=(
                    DIMENSION_TOLERANCE
                ),
            ):
                raise RuntimeError(
                    (
                        "Geometry dimensions differ "
                        f"for {variant.sheet}/"
                        f"{variant.profile} "
                        f"on axis {axis}."
                    )
                )


# =========================================================
# Render one variant
# =========================================================

def render_variant(
    variant: Variant,
    *,
    views: int,
    size: int,
    samples: int,
    keep_stills: bool,
    reuse_render: bool,
) -> Path:
    if (
        reuse_render
        and variant
        .contact_sheet_path
        .is_file()
    ):
        print(
            (
                "Reuse render: "
                f"{variant.contact_sheet_path}"
            )
        )

        return (
            variant
            .contact_sheet_path
        )

    if variant.render_root.exists():
        shutil.rmtree(
            variant.render_root
        )

    variant.render_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    print()

    print(
        "-" * 72
    )

    print(
        (
            f"{variant.sheet} / "
            f"{variant.profile} / "
            f"{variant.implementation}"
        )
    )

    print(
        "-" * 72
    )

    started_at = (
        time.perf_counter()
    )

    contact_path = (
        render_turntable(
            variant.model_path,
            variant.render_root,

            views=views,

            size=size,

            samples=samples,

            keep_stills=(
                keep_stills
            ),

            # Critical:
            #
            # do NOT replace the MATERIAL implementation
            # with the neutral geometry-preview material.
            preserve_material=True,
        )
    )

    elapsed = (
        time.perf_counter()
        - started_at
    )

    if not contact_path.is_file():
        raise RuntimeError(
            (
                "Variant render did not "
                "produce a contact sheet: "
                f"{contact_path}"
            )
        )

    print(
        (
            "Variant rendered in "
            f"{elapsed:.3f}s"
        )
    )

    return contact_path


# =========================================================
# Image helpers
# =========================================================

def _load_image_pixels(
    path: Path,
) -> tuple[
    array,
    int,
    int,
]:
    image = (
        bpy.data.images.load(
            str(
                path.resolve()
            ),
            check_existing=False,
        )
    )

    try:
        image.update()

        width = int(
            image.size[0]
        )

        height = int(
            image.size[1]
        )

        if (
            width <= 0
            or height <= 0
        ):
            raise RuntimeError(
                (
                    "Invalid image size: "
                    f"{path}"
                )
            )

        pixels = (
            array(
                "f",
                [
                    0.0
                ],
            )
            * (
                width
                * height
                * 4
            )
        )

        image.pixels.foreach_get(
            pixels
        )

        return (
            pixels,
            width,
            height,
        )

    finally:
        bpy.data.images.remove(
            image
        )


def _image_size(
    path: Path,
) -> tuple[
    int,
    int,
]:
    image = (
        bpy.data.images.load(
            str(
                path.resolve()
            ),
            check_existing=False,
        )
    )

    try:
        image.update()

        return (
            int(
                image.size[0]
            ),
            int(
                image.size[1]
            ),
        )

    finally:
        bpy.data.images.remove(
            image
        )


# =========================================================
# Final matrix
# =========================================================

def build_comparison_matrix(
    cells: dict[
        tuple[
            str,
            str,
        ],
        Path,
    ],
    *,
    profiles: list[str],
    implementations: list[str],
    output_path: Path,
    gutter: int,
) -> dict[str, Any]:
    """
    Layout:

                           implementations →

            projected-color-v1.2 | uv-bake-v2

        L2      contact sheet    | contact sheet

        L4      contact sheet    | contact sheet

        L8      contact sheet    | contact sheet

        L10     contact sheet    | contact sheet


    No Pillow/ImageMagick dependency is required.

    Composition happens directly through Blender image
    buffers.
    """

    available_paths = [
        path
        for path
        in cells.values()
        if path.is_file()
    ]

    if not available_paths:
        raise RuntimeError(
            (
                "No rendered contact sheet "
                "is available for composition."
            )
        )

    (
        tile_width,
        tile_height,
    ) = (
        _image_size(
            available_paths[
                0
            ]
        )
    )

    # -----------------------------------------------------
    # Every implementation must use the exact same
    # turntable dimensions.
    # -----------------------------------------------------

    for path in (
        available_paths[
            1:
        ]
    ):
        (
            width,
            height,
        ) = (
            _image_size(
                path
            )
        )

        if (
            width != tile_width
            or height != tile_height
        ):
            raise RuntimeError(
                (
                    "Contact-sheet dimensions "
                    "are inconsistent.\n"
                    f"Expected: "
                    f"{tile_width}x{tile_height}\n"
                    f"Received: "
                    f"{width}x{height}\n"
                    f"File: {path}"
                )
            )

    columns = len(
        implementations
    )

    rows = len(
        profiles
    )

    output_width = (
        columns
        * tile_width
        + max(
            0,
            columns - 1,
        )
        * gutter
    )

    output_height = (
        rows
        * tile_height
        + max(
            0,
            rows - 1,
        )
        * gutter
    )

    pixel_count = (
        output_width
        * output_height
    )

    destination = (
        array(
            "f",
            BACKGROUND_COLOR,
        )
        * pixel_count
    )

    source_row_values = (
        tile_width
        * 4
    )

    layout_cells = []

    # -----------------------------------------------------
    # Blender images have bottom-left pixel origin.
    #
    # profiles[0] must appear visually on TOP, so rows are
    # reversed when calculating destination Y.
    # -----------------------------------------------------

    for (
        profile_index,
        profile,
    ) in enumerate(
        profiles
    ):
        destination_row = (
            rows
            - 1
            - profile_index
        )

        destination_y = (
            destination_row
            * (
                tile_height
                + gutter
            )
        )

        for (
            implementation_index,
            implementation,
        ) in enumerate(
            implementations
        ):
            destination_x = (
                implementation_index
                * (
                    tile_width
                    + gutter
                )
            )

            key = (
                profile,
                implementation,
            )

            source_path = (
                cells.get(
                    key
                )
            )

            cell_info = {
                "profile": profile,

                "implementation": (
                    implementation
                ),

                "column": (
                    implementation_index
                ),

                "row": (
                    profile_index
                ),

                "x": (
                    destination_x
                ),

                "y": (
                    destination_y
                ),

                "width": (
                    tile_width
                ),

                "height": (
                    tile_height
                ),

                "image": (
                    str(
                        source_path
                    )
                    if source_path
                    is not None
                    else None
                ),

                "present": False,
            }

            layout_cells.append(
                cell_info
            )

            # ---------------------------------------------
            # Missing variants are deliberately left with
            # the neutral background when
            # --continue-on-error is active.
            # ---------------------------------------------

            if (
                source_path is None
                or not source_path.is_file()
            ):
                continue

            (
                source,
                width,
                height,
            ) = (
                _load_image_pixels(
                    source_path
                )
            )

            if (
                width != tile_width
                or height
                != tile_height
            ):
                raise RuntimeError(
                    (
                        "Unexpected source image "
                        "dimensions during copy."
                    )
                )

            for local_y in range(
                tile_height
            ):
                source_start = (
                    local_y
                    * source_row_values
                )

                source_end = (
                    source_start
                    + source_row_values
                )

                target_start = (
                    (
                        (
                            destination_y
                            + local_y
                        )
                        * output_width
                        + destination_x
                    )
                    * 4
                )

                target_end = (
                    target_start
                    + source_row_values
                )

                destination[
                    target_start:
                    target_end
                ] = (
                    source[
                        source_start:
                        source_end
                    ]
                )

            cell_info[
                "present"
            ] = True

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    image = (
        bpy.data.images.new(
            name=(
                "MeshvennMaterialComparison"
            ),
            width=(
                output_width
            ),
            height=(
                output_height
            ),
            alpha=True,
        )
    )

    try:
        image.pixels.foreach_set(
            destination
        )

        image.filepath_raw = str(
            output_path.resolve()
        )

        image.file_format = (
            "PNG"
        )

        image.save()

    finally:
        bpy.data.images.remove(
            image
        )

    if not output_path.is_file():
        raise RuntimeError(
            (
                "Comparison matrix was "
                "not generated."
            )
        )

    return {
        "image": str(
            output_path
        ),

        "width": (
            output_width
        ),

        "height": (
            output_height
        ),

        "tile_width": (
            tile_width
        ),

        "tile_height": (
            tile_height
        ),

        "gutter": (
            gutter
        ),

        "rows": list(
            profiles
        ),

        "columns": list(
            implementations
        ),

        "cells": (
            layout_cells
        ),
    }


# =========================================================
# One sheet
# =========================================================

def process_sheet(
    comparison_root: Path,
    *,
    sheet: str,
    profiles: list[str],
    implementations: list[str],
    args: argparse.Namespace,
) -> dict[str, Any]:
    print()

    print(
        "=" * 72
    )

    print(
        (
            "MATERIAL COMPARISON | "
            f"{sheet}"
        )
    )

    print(
        "=" * 72
    )

    sheet_root = (
        comparison_root
        / sheet
    )

    result: dict[
        str,
        Any,
    ] = {
        "sheet": sheet,

        "profiles": list(
            profiles
        ),

        "implementations": list(
            implementations
        ),

        "views": (
            args.views
        ),

        "size": (
            args.size
        ),

        "samples": (
            args.samples
        ),

        "variants": {},

        "errors": [],
    }

    rendered_cells: dict[
        tuple[
            str,
            str,
        ],
        Path,
    ] = {}

    # -----------------------------------------------------
    # Each profile must use identical geometry across all
    # MATERIAL implementations.
    # -----------------------------------------------------

    for profile in (
        profiles
    ):
        variants: list[
            Variant
        ] = []

        for implementation in (
            implementations
        ):
            try:
                variant = (
                    load_variant(
                        comparison_root,
                        sheet=sheet,
                        profile=profile,
                        implementation=(
                            implementation
                        ),
                    )
                )

                variants.append(
                    variant
                )

            except Exception as exc:
                result[
                    "errors"
                ].append(
                    {
                        "profile": profile,

                        "implementation": (
                            implementation
                        ),

                        "phase": (
                            "load"
                        ),

                        "type": (
                            type(
                                exc
                            ).__name__
                        ),

                        "error": str(
                            exc
                        ),
                    }
                )

                if (
                    not args
                    .continue_on_error
                ):
                    raise

        if variants:
            try:
                validate_geometry_parity(
                    variants
                )

            except Exception as exc:
                result[
                    "errors"
                ].append(
                    {
                        "profile": profile,

                        "phase": (
                            "geometry-parity"
                        ),

                        "type": (
                            type(
                                exc
                            ).__name__
                        ),

                        "error": str(
                            exc
                        ),
                    }
                )

                if (
                    not args
                    .continue_on_error
                ):
                    raise

                continue

        # -------------------------------------------------
        # Render each implementation using the same:
        #
        # views
        # size
        # Cycles samples
        # renderer
        # lighting
        # material preservation
        # -------------------------------------------------

        for variant in (
            variants
        ):
            key = (
                profile,
                variant.implementation,
            )

            started_at = (
                time.perf_counter()
            )

            try:
                contact_path = (
                    render_variant(
                        variant,
                        views=(
                            args.views
                        ),
                        size=(
                            args.size
                        ),
                        samples=(
                            args.samples
                        ),
                        keep_stills=(
                            args.keep_stills
                        ),
                        reuse_render=(
                            args.reuse_renders
                        ),
                    )
                )

                elapsed = (
                    time.perf_counter()
                    - started_at
                )

                rendered_cells[
                    key
                ] = contact_path

                result[
                    "variants"
                ][
                    (
                        f"{profile}/"
                        f"{variant.implementation}"
                    )
                ] = {
                    "generated": True,

                    "model": str(
                        variant.model_path
                    ),

                    "variant_manifest": str(
                        variant
                        .manifest_path
                    ),

                    "contact_sheet": str(
                        contact_path
                    ),

                    "elapsed_seconds": (
                        elapsed
                    ),
                }

            except Exception as exc:
                elapsed = (
                    time.perf_counter()
                    - started_at
                )

                result[
                    "variants"
                ][
                    (
                        f"{profile}/"
                        f"{variant.implementation}"
                    )
                ] = {
                    "generated": False,

                    "elapsed_seconds": (
                        elapsed
                    ),

                    "error": str(
                        exc
                    ),
                }

                result[
                    "errors"
                ].append(
                    {
                        "profile": profile,

                        "implementation": (
                            variant
                            .implementation
                        ),

                        "phase": (
                            "render"
                        ),

                        "type": (
                            type(
                                exc
                            ).__name__
                        ),

                        "error": str(
                            exc
                        ),
                    }
                )

                if (
                    not args
                    .continue_on_error
                ):
                    raise

    # -----------------------------------------------------
    # Build the large side-by-side board.
    # -----------------------------------------------------

    matrix_path = (
        sheet_root
        / "material_comparison.png"
    )

    matrix_info = (
        build_comparison_matrix(
            rendered_cells,

            profiles=profiles,

            implementations=(
                implementations
            ),

            output_path=(
                matrix_path
            ),

            gutter=(
                args.gutter
            ),
        )
    )

    result[
        "matrix"
    ] = (
        matrix_info
    )

    result[
        "success"
    ] = (
        len(
            result[
                "errors"
            ]
        )
        == 0
    )

    result_path = (
        sheet_root
        / "render_comparison.json"
    )

    write_json(
        result_path,
        result,
    )

    print()

    print(
        (
            "Comparison matrix: "
            f"{matrix_path}"
        )
    )

    print(
        (
            "Layout manifest: "
            f"{result_path}"
        )
    )

    return result


# =========================================================
# Markdown index
# =========================================================

def write_markdown_index(
    comparison_root: Path,
    *,
    sheets: list[str],
    profiles: list[str],
    implementations: list[str],
) -> Path:
    path = (
        comparison_root
        / "MATERIAL_COMPARISON.md"
    )

    lines = [
        "# Meshvenn Material Comparison",
        "",
        "Generated visual comparison of MATERIAL implementations.",
        "",
        "## Matrix layout",
        "",
        "Columns:",
        "",
    ]

    for (
        index,
        implementation,
    ) in enumerate(
        implementations,
        start=1,
    ):
        lines.append(
            (
                f"{index}. "
                f"`{implementation}`"
            )
        )

    lines.extend(
        [
            "",
            "Rows:",
            "",
        ]
    )

    for (
        index,
        profile,
    ) in enumerate(
        profiles,
        start=1,
    ):
        lines.append(
            (
                f"{index}. "
                f"`{profile}`"
            )
        )

    lines.extend(
        [
            "",
            "Every cell uses the same turntable angles, "
            "camera logic, lighting and Cycles settings.",
            "",
        ]
    )

    for sheet in sheets:
        relative = (
            Path(sheet)
            / "material_comparison.png"
        )

        lines.extend(
            [
                f"## {sheet}",
                "",
                (
                    f"![{sheet} MATERIAL comparison]"
                    f"({relative.as_posix()})"
                ),
                "",
            ]
        )

    path.write_text(
        "\n".join(
            lines
        ),
        encoding="utf-8",
    )

    return path


# =========================================================
# Main
# =========================================================

def main() -> None:
    args = (
        parse_args()
    )

    validate_args(
        args
    )

    comparison_root = (
        args
        .comparison_root
        .resolve()
    )

    sheets = (
        discover_sheets(
            comparison_root,
            args.sheets,
        )
    )

    print(
        "=" * 72
    )

    print(
        "MESHVENN MATERIAL VISUAL COMPARISON"
    )

    print(
        "=" * 72
    )

    print(
        (
            "Comparison root: "
            f"{comparison_root}"
        )
    )

    print(
        (
            "Sheets: "
            + ", ".join(
                sheets
            )
        )
    )

    print(
        (
            "Profiles: "
            + ", ".join(
                args.profiles
            )
        )
    )

    print(
        (
            "Implementations: "
            + ", ".join(
                args.implementations
            )
        )
    )

    print(
        (
            "Views: "
            f"{args.views}"
        )
    )

    print(
        (
            "Tile size: "
            f"{args.size}px"
        )
    )

    print(
        (
            "Cycles samples: "
            f"{args.samples}"
        )
    )

    started_at = (
        time.perf_counter()
    )

    results = {}

    failures = []

    for (
        index,
        sheet,
    ) in enumerate(
        sheets,
        start=1,
    ):
        print()

        print(
            (
                f"[{index}/{len(sheets)}] "
                f"{sheet}"
            )
        )

        try:
            result = (
                process_sheet(
                    comparison_root,

                    sheet=sheet,

                    profiles=(
                        args.profiles
                    ),

                    implementations=(
                        args
                        .implementations
                    ),

                    args=args,
                )
            )

            results[
                sheet
            ] = (
                result
            )

            if not result[
                "success"
            ]:
                failures.append(
                    sheet
                )

        except Exception as exc:
            results[
                sheet
            ] = {
                "success": False,

                "error": str(
                    exc
                ),

                "type": (
                    type(
                        exc
                    ).__name__
                ),
            }

            failures.append(
                sheet
            )

            if (
                not args
                .continue_on_error
            ):
                raise

    markdown_path = (
        write_markdown_index(
            comparison_root,

            sheets=sheets,

            profiles=(
                args.profiles
            ),

            implementations=(
                args
                .implementations
            ),
        )
    )

    elapsed = (
        time.perf_counter()
        - started_at
    )

    global_manifest = {
        "success": (
            len(
                failures
            )
            == 0
        ),

        "comparison_root": str(
            comparison_root
        ),

        "sheets": (
            results
        ),

        "sheet_order": (
            sheets
        ),

        "profile_order": (
            args.profiles
        ),

        "implementation_order": (
            args
            .implementations
        ),

        "views": (
            args.views
        ),

        "render_size": (
            args.size
        ),

        "cycles_samples": (
            args.samples
        ),

        "gutter": (
            args.gutter
        ),

        "markdown": str(
            markdown_path
        ),

        "failures": (
            failures
        ),

        "elapsed_seconds": (
            elapsed
        ),
    }

    manifest_path = (
        comparison_root
        / "render_comparison.json"
    )

    write_json(
        manifest_path,
        global_manifest,
    )

    print()

    print(
        "=" * 72
    )

    print(
        "MATERIAL COMPARISON SUMMARY"
    )

    print(
        "=" * 72
    )

    print(
        (
            "Sheets: "
            f"{len(sheets)}"
        )
    )

    print(
        (
            "Failures: "
            f"{len(failures)}"
        )
    )

    print(
        (
            "Elapsed: "
            f"{elapsed:.2f}s"
        )
    )

    print(
        (
            "Index: "
            f"{markdown_path}"
        )
    )

    print(
        (
            "Manifest: "
            f"{manifest_path}"
        )
    )

    if failures:
        raise SystemExit(
            1
        )


if __name__ == "__main__":
    main()